# Auto-generated from the live NextAccounting Chart of Accounts for Eminent 2022
# Limited (c36.nextaccounting.co.tz), captured 2026-09-03 after the Round 2 COA
# restructuring (EWURA removal, Puma/Driver Mileage/Bypass accounts, tax and
# border-charge consolidation). Kept in numeric account-code order.
#
# Each row: (code, name, statement_class, account_group, normal_balance)
#   statement_class in {asset, liability, equity, income, cogs, expense}
#   normal_balance in {debit, credit}
COA_SEED = [
    ("1000", 'Bank', "asset", 'Bank', "debit"),
    ("1010", 'CRDB TZS', "asset", 'Bank', "debit"),
    ("1011", 'CRDB USD', "asset", 'Bank', "debit"),
    ("1012", 'NMB TZS', "asset", 'Bank', "debit"),
    ("1013", 'NMB USD', "asset", 'Bank', "debit"),
    ("1021", 'Petty Cash', "asset", 'Cash on Hand', "debit"),
    ("1022", 'Cash on Hand at HQ', "asset", 'Cash on Hand', "debit"),
    ("1023", 'Operating Cash- Director', "asset", 'Cash on Hand', "debit"),
    ("1024", 'Mobile Money', "asset", 'Cash on Hand', "debit"),
    ("1100", 'Account Receivable (A/R)', "asset", 'Accounts Receivable (A/R)', "debit"),
    ("1101", 'Invoice Receivable', "asset", 'Accounts Receivable (A/R)', "debit"),
    ("1102", 'Open Balance Receivable', "asset", 'Accounts Receivable (A/R)', "debit"),
    ("1103", 'Supplier Refund Receivable', "asset", 'Accounts Receivable (A/R)', "debit"),
    ("1104", 'Safari Imprest', "asset", 'Accounts Receivable (A/R)', "debit"),
    ("1105", 'Safari Imprest - Refund', "asset", 'Accounts Receivable (A/R)', "debit"),
    ("1200", 'Inventory', "asset", 'Stock', "debit"),
    ("1210", 'Inventory Asset', "asset", 'Stock', "debit"),
    ("1300", 'Other current asset', "asset", 'Other Current Assets', "debit"),
    ("1301", 'Loan to Staff', "asset", 'Other Current Assets', "debit"),
    ("1302", 'Prepaid Expenses', "asset", 'Other Current Assets', "debit"),
    ("1303", 'Driver Fuel Reconcile', "asset", 'Other Current Assets', "debit"),
    ("1304", 'Puma Account', "asset", 'Cash on Hand', "debit"),
    ("1500", 'Furniture and Fixtures', "asset", 'Furniture and Fixtures', "debit"),
    ("1510", 'Computer Equipment', "asset", 'Computer Equipment', "debit"),
    ("1530", 'Motor Vehicles', "asset", 'Motor Vehicles', "debit"),
    ("1600", 'Accumulated Depreciation', "asset", 'Accumulated Depreciation', "debit"),
    ("2000", 'Accounts Payable (A/P)', "liability", 'Accounts Payable (A/P)', "credit"),
    ("2001", 'Bills Payable', "liability", 'Accounts Payable (A/P)', "credit"),
    ("2002", 'Open Balance Payable', "liability", 'Accounts Payable (A/P)', "credit"),
    ("2003", 'Customer Advance Payment', "liability", 'Accounts Payable (A/P)', "credit"),
    ("2004", 'Pay in advance ac', "liability", 'Accounts Payable (A/P)', "credit"),
    ("2005", 'Consultation fee', "liability", 'Accounts Payable (A/P)', "credit"),
    ("2006", 'Safari Retirement (Payable)', "liability", 'Accounts Payable (A/P)', "credit"),
    ("2007", 'Sale Return Payables', "liability", 'Accounts Payable (A/P)', "credit"),
    ("2010", 'Tax Payable', "liability", 'Accounts Payable (A/P)', "credit"),
    ("2011", 'VAT Payable', "liability", 'Accounts Payable (A/P)', "credit"),
    ("2012", 'Withholding Tax', "expense", 'Administration Expenses', "debit"),
    ("2100", 'Payroll Liability', "liability", 'Payroll Liability', "credit"),
    ("2101", 'Net Salary Payable', "liability", 'Payroll Liability', "credit"),
    ("2102", 'Health Care/Insurance Payable', "liability", 'Payroll Liability', "credit"),
    ("2103", 'Social Security Fund Payable', "liability", 'Payroll Liability', "credit"),
    ("2104", 'Net Amount Payable (Mid Month)', "liability", 'Payroll Liability', "credit"),
    ("2105", 'TRA SDL Payable', "liability", 'Payroll Liability', "credit"),
    ("2106", 'PAYE Payable', "liability", 'Payroll Liability', "credit"),
    ("2107", 'HESLB Payable', "liability", 'Payroll Liability', "credit"),
    ("2108", 'WCF Payable', "liability", 'Payroll Liability', "credit"),
    ("2109", 'Salary Advance Third Party Payable', "liability", 'Payroll Liability', "credit"),
    ("2301", 'Business Loans', "liability", 'Other Current Liability', "credit"),
    ("2302", 'Work In Capital', "liability", 'Other Current Liability', "credit"),
    ("2303", 'Advance Sale', "liability", 'Other Current Liability', "credit"),
    ("3001", 'Members Equity', "equity", 'Equity', "credit"),
    ("3002", 'Owners Contributions', "equity", 'Equity', "credit"),
    ("3003", 'Share Capital Account', "equity", 'Equity', "credit"),
    ("3004", 'Member Drawings', "equity", 'Equity', "credit"),
    ("3005", 'Open Balance Equity', "equity", 'Equity', "credit"),
    ("3100", 'Retained Earnings', "equity", 'Retained Earnings', "credit"),
    ("3101", 'Dividends', "equity", 'Retained Earnings', "debit"),
    ("4001", 'Sales', "income", 'Income', "credit"),
    ("4002", 'Delay Charge Fee', "income", 'Income', "credit"),
    ("4003", 'Transportation Sales', "income", 'Income', "credit"),
    ("4004", 'Motor Repairment Compensation', "income", 'Income', "credit"),
    ("4005", 'Un-categorized Income', "income", 'Income', "credit"),
    ("4101", 'Asset Disposal Gain', "income", 'Non Cash Income', "credit"),
    ("5000", 'Cost of Goods Sold', "cogs", 'Cost of Goods Sold', "debit"),
    ("5001", 'Loading / Offloading Fee', "cogs", 'Cost of Goods Sold', "debit"),
    ("5002", 'Yellow Card', "cogs", 'Cost of Goods Sold', "debit"),
    ("5003", 'Container fee', "cogs", 'Cost of Goods Sold', "debit"),
    ("5004", 'Delay Charges', "cogs", 'Cost of Goods Sold', "debit"),
    ("5005", 'Covid 19', "cogs", 'Cost of Goods Sold', "debit"),
    ("5006", 'Exit', "cogs", 'Cost of Goods Sold', "debit"),
    ("5007", 'DEMURAGE & DROP OFF CHARGES', "cogs", 'Cost of Goods Sold', "debit"),
    ("5100", 'Boarder Charges', "cogs", 'Cost of Goods Sold', "debit"),
    ("5101", 'Toll Gate', "cogs", 'Cost of Goods Sold', "debit"),
    ("5109", 'Council', "cogs", 'Cost of Goods Sold', "debit"),
    ("5110", 'Peages', "cogs", 'Cost of Goods Sold', "debit"),
    ("5111", 'Bypass', "cogs", 'Cost of Goods Sold', "debit"),
    ("5200", 'Trip Driver Expenses', "cogs", 'Cost of Goods Sold', "debit"),
    ("5202", 'Trip Fuel', "cogs", 'Cost of Goods Sold', "debit"),
    ("5203", 'Trip Miscelleneous Cost', "cogs", 'Cost of Goods Sold', "debit"),
    ("5204", 'Dispatch Allowance', "cogs", 'Cost of Goods Sold', "debit"),
    ("5205", 'Trip Transaction Charges', "cogs", 'Cost of Goods Sold', "debit"),
    ("5206", 'Driver Mileage Account', "asset", 'Accounts Receivable (A/R)', "debit"),
    ("6000", 'Administration Expenses', "expense", 'Administration Expenses', "debit"),
    ("6002", 'CORPORATE TAX', "expense", 'Administration Expenses', "debit"),
    ("6004", 'Advocate Fees (WT)', "expense", 'Administration Expenses', "debit"),
    ("6005", 'Stationery and Printing', "expense", 'Administration Expenses', "debit"),
    ("6006", 'CARRIERS LIABILITY INSURANCE', "expense", 'Administration Expenses', "debit"),
    ("6007", 'Business Licenses', "expense", 'Administration Expenses', "debit"),
    ("6008", 'C28 License', "expense", 'Administration Expenses', "debit"),
    ("6009", 'COMESA', "expense", 'Administration Expenses', "debit"),
    ("6010", 'Telephone and Communication', "expense", 'Administration Expenses', "debit"),
    ("6011", 'Accounting and Audit Fees', "expense", 'Administration Expenses', "debit"),
    ("6012", 'Transport Cost', "expense", 'Administration Expenses', "debit"),
    ("6013", 'Bank Charges', "expense", 'Administration Expenses', "debit"),
    ("6014", 'OSHA', "expense", 'Administration Expenses', "debit"),
    ("6015", 'Transaction Charges', "expense", 'Administration Expenses', "debit"),
    ("6016", 'Stamp Duty', "expense", 'Administration Expenses', "debit"),
    ("6017", 'Motor Insurance', "expense", 'Administration Expenses', "debit"),
    ("6018", 'Rent for Offices', "expense", 'Administration Expenses', "debit"),
    ("6019", 'LATRA', "expense", 'Administration Expenses', "debit"),
    ("6020", 'Truck TRA Charges', "expense", 'Administration Expenses', "debit"),
    ("6022", 'Garden Cleaning', "expense", 'Administration Expenses', "debit"),
    ("6100", 'Office Expenses', "expense", 'Administration Expenses', "debit"),
    ("6101", 'Office Supplies', "expense", 'Administration Expenses', "debit"),
    ("6102", 'Office Utilities', "expense", 'Administration Expenses', "debit"),
    ("6150", 'Salaries and Wages', "expense", 'Administration Expenses', "debit"),
    ("6151", 'PAYE', "expense", 'Administration Expenses', "debit"),
    ("6152", 'TRA SDL', "expense", 'Administration Expenses', "debit"),
    ("6153", 'Worker Compensation Fund (WCF)', "expense", 'Administration Expenses', "debit"),
    ("6154", 'Net Salary (BANK/CASH)', "expense", 'Administration Expenses', "debit"),
    ("6155", 'NSSF Contribution', "expense", 'Administration Expenses', "debit"),
    ("6156", 'Staff Transport Allowance', "expense", 'Administration Expenses', "debit"),
    ("6157", 'Annual Leave Salary', "expense", 'Administration Expenses', "debit"),
    ("6158", 'Advance Salary', "expense", 'Administration Expenses', "debit"),
    ("6200", 'Operation Expenses', "expense", 'Operation Expenses', "debit"),
    ("6201", 'Inspection fee', "expense", 'Operation Expenses', "debit"),
    ("6202", 'Motor Fuel', "expense", 'Operation Expenses', "debit"),
    ("6203", 'Rollers', "expense", 'Operation Expenses', "debit"),
    ("6204", 'Container tracking device', "expense", 'Operation Expenses', "debit"),
    ("6205", 'Security Services (WT)', "expense", 'Operation Expenses', "debit"),
    ("6206", 'Fines & Penalties', "expense", 'Operation Expenses', "debit"),
    ("6207", 'Advertising and Promotion', "expense", 'Operation Expenses', "debit"),
    ("6208", 'Software Services', "expense", 'Operation Expenses', "debit"),
    ("6209", 'Weight Bridge', "expense", 'Operation Expenses', "debit"),
    ("6210", 'Water Bill', "expense", 'Operation Expenses', "debit"),
    ("6211", 'Labour Charge', "expense", 'Operation Expenses', "debit"),
    ("6212", 'Provision Tax', "expense", 'Operation Expenses', "debit"),
    ("6213", 'Parking Fee', "expense", 'Operation Expenses', "debit"),
    ("6214", 'Staff Training and Welfare', "expense", 'Operation Expenses', "debit"),
    ("6215", 'Truck Operations', "expense", 'Operation Expenses', "debit"),
    ("6216", 'Electricity Bills', "expense", 'Operation Expenses', "debit"),
    ("6217", 'Others', "expense", 'Operation Expenses', "debit"),
    ("6218", 'Stock Shortage', "expense", 'Operation Expenses', "debit"),
    ("6220", 'Billboard Advertisement', "expense", 'Operation Expenses', "debit"),
    ("6221", 'Property Tax', "expense", 'Operation Expenses', "debit"),
    ("6222", 'Medical Allowance', "expense", 'Operation Expenses', "debit"),
    ("6300", 'Staff Travelling', "expense", 'Operation Expenses', "debit"),
    ("6301", 'Cash Travelling', "expense", 'Operation Expenses', "debit"),
    ("6350", 'Motor Repair and Maintenance', "expense", 'Operation Expenses', "debit"),
    ("6351", 'Motor Spare Part', "expense", 'Operation Expenses', "debit"),
    ("6352", 'Oil & Grease', "expense", 'Operation Expenses', "debit"),
    ("6353", 'Motor Service Charge (Labour)', "expense", 'Operation Expenses', "debit"),
    ("6354", 'Trucks Repair and Maintenance', "expense", 'Operation Expenses', "debit"),
    ("6355", 'EFD Equipment', "expense", 'Operation Expenses', "debit"),
    ("6400", 'Discount', "expense", 'Operation Expenses', "debit"),
    ("6401", 'Cash Sales Discount', "expense", 'Operation Expenses', "debit"),
    ("6500", 'Non-Cash Expense', "expense", 'Non Cash Expense', "debit"),
    ("6501", 'Depreciation Asset Cost', "expense", 'Non Cash Expense', "debit"),
    ("6502", 'Asset Disposal Loss', "expense", 'Non Cash Expense', "debit"),
    ("6901", 'Non-Operating Expense', "expense", 'Uncategorized Expenses', "debit"),
    ("6902", 'Exchange Gain or Loss', "expense", 'Uncategorized Expenses', "debit"),
    ("6903", 'Un-categorized Expenses', "expense", 'Operation Expenses', "debit"),
]
